export enum TaskErrorCodes {
  TASK_NOT_FOUND = 'T1',
  INVALID_TASK_DATA = 'T2',
  INVALID_TITLE = 'T3',
  INVALID_DESCRIPTION = 'T4',
  INVALID_USER_ID = 'T5',
  TASK_CREATION_FAILED = 'T6',
  UNKNOWN_ERROR = 'T7',
}
