export enum AuthErrorCode {
    INVALID_CREDENTIALS = 'AUTH1',
    TOKEN_EXPIRED = 'AUTH2',   
    INVALID_TOKEN = 'AUTH3',
    UNAUTHORIZED = 'AUTH4',
    INVALID_JWT_SECRET = 'AUTH5',
    UNKNOWN_ERROR = 'AUTH6'
}