export enum ErrorCode {

  USER_NOT_FOUND = 'U1',
  EMAIL_ALREADY_EXISTS = 'U2',
  USERNAME_ALREADY_EXISTS = 'U3',
  INVALID_USER_DATA = 'U4',
  INVALID_USERNAME = 'U5',
  INVALID_EMAIL = 'U6',
  USER_CREATION_FAILED = 'U7',

  TASK_NOT_FOUND = 'T1',
  INVALID_TASK_DATA = 'T2',
  INVALID_TITLE = 'T3',
  INVALID_DESCRIPTION = 'T4',
  TASK_CREATION_FAILED = 'T5',
  
  INVALID_PASSWORD = 'A1',
  INVALID_TOKEN = 'A2',
  
  INVALID_JSON_FORMAT = 'F1',
  INVALID_ID_FORMAT = 'F2',
}