export enum UserErrorCodes {
    INVALID_USERNAME = 'U1',
    INVALID_EMAIL = 'U2',
    INVALID_PASSWORD = 'U3',
    INVALID_TOKEN = 'U4',
    USER_NOT_FOUND = 'U5',
    EMAIL_ALREADY_EXISTS = 'U6',
    USERNAME_ALREADY_EXISTS = 'U7',
    INVALID_USER_DATA = 'U8',
    USER_CREATION_FAILED = 'U9'

}